# Usa una imagen oficial de Node.js
FROM node:22

# Establece el directorio de trabajo
WORKDIR /app

# Expone el puerto
EXPOSE 5173

# Comando para iniciar el servidor en modo producción
CMD ["npm", "run", "dev"]
